# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.TextField()),
                ('post_creator', models.CharField(max_length=100)),
                ('amount_goal', models.IntegerField()),
                ('detailed_description', models.TextField()),
                ('title_image', models.ImageField(upload_to='media/images')),
                ('already_funded', models.IntegerField()),
            ],
        ),
    ]
